micronaut:
  application:
    name: renalo
  security:
    authentication: bearer
    intercept-url-map:
      - pattern: /assets/**
        access:
          - isAnonymous()
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${RENALO_JWT_SECRET:`change-this-development-secret-change-before-production`}
  router:
    static-resources:
      default:
        enabled: true
        mapping: /assets/**
        paths: classpath:public/assets

datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://localhost:5432/renalo`}
    username: ${JDBC_USER:renalo}
    password: ${JDBC_PASSWORD:renalo}
    driver-class-name: org.postgresql.Driver

flyway:
  datasources:
    default:
      enabled: true

renalo:
  public-url: ${RENALO_PUBLIC_URL:`http://localhost:8080`}
  auth:
    access-token-expiration-seconds: 1800
  activation-token:
    delay: PT1S
  default-admin:
    username: ${RENALO_DEFAULT_ADMIN_USERNAME:admin}
